server {
    listen       80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # 容器/Compose 健康检查端点
    location = /healthz {
        access_log off;
        default_type text/plain;
        return 200 'ok';
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:js|css|svg|png|ico)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
